### ISSUE TITLE
static files not found

### ISSUE THREAD

**Issue by dandani-cs** [dandani-cs/microtechnics_ims#13]
Empbase.html still uses absolute paths in referencing static files. Either change base html to Admin base or change static files

powershell in inventory/view
![image](https://user-images.githubusercontent.com/19799004/114847769-a633a580-9e10-11eb-9dd5-8f9170bfd393.png)

empbase.html
![image](https://user-images.githubusercontent.com/19799004/114847864-be0b2980-9e10-11eb-8a6d-156e6bb78ec6.png)

**Comment by LednirNaabus** [comment]
modified the paths on empbase.html to this:
![image](https://user-images.githubusercontent.com/22275889/114856173-602f0f80-9e19-11eb-9ba0-2394cbe5837a.png)


When running the server:
![image](https://user-images.githubusercontent.com/22275889/114853961-e8f87c00-9e16-11eb-9ba3-11b186d229a8.png)


EDIT: first pic

**Comment by dandani-cs** [comment]
pull request when convenient. thank you.
